"""Add users table

Revision ID: 2394890a2411
Revises: 72887cdef64e
Create Date: 2024-11-14 21:02:29.755030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2394890a2411'
down_revision = '72887cdef64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_testimonials_client_id_clients', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_testimonials_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_testimonials_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_testimonials_client_id_clients', 'clients', ['client_id'], ['id'])
        batch_op.drop_column('user_id')

    op.drop_table('users')
    # ### end Alembic commands ###
