"""change user_id from user.id to user.auth0_id

Revision ID: 4964e1b7cd12
Revises: e07016005407
Create Date: 2024-11-17 20:03:38.740359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4964e1b7cd12'
down_revision = 'e07016005407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_testimonials_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_testimonials_user_id_users'), 'users', ['user_id'], ['auth0_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_testimonials_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_testimonials_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
