"""add audio to Showtable

Revision ID: c0153e914ca0
Revises: 4f7a9f335f28
Create Date: 2024-11-04 14:02:22.038755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0153e914ca0'
down_revision = '4f7a9f335f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_column('audio')

    # ### end Alembic commands ###
