"""add link attribute to sponsors table

Revision ID: e126393035ee
Revises: 9f92560782ec
Create Date: 2024-11-05 10:27:12.846776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e126393035ee'
down_revision = '9f92560782ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
